---      
- name: install autofs and start
  hosts: all
  tasks: 
    - name: install autofs
      dnf:
        name: autofs
        state: present
    - name: start autofs service
      service:
        name: autofs
        state: started
